[workspace]
authors = ["Bryson Tang <brysontang@gmail.com>"]
channels = ["conda-forge"]
name = "crystallize"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
test = "pytest -q"
cov  = "pytest --cov=crystallize --cov-report=term-missing"
lint = "ruff check crystallize tests"

[dependencies]
python = "3.11.*"
pytest = "*"
pytest-cov = "*"
ruff = "*"
scipy = ">=1.16.0,<2"
pyyaml = ">=6.0.2,<7"
