blank_issues_enabled: false
contact_links:
  - name: Project Discussions
    url: https://github.com/brysontang/crystallize/discussions
    about: Please ask general questions here instead of opening issues.
