METADATA_FILENAME = "metadata.json"
BASELINE_CONDITION = "baseline"
REPLICATE_KEY = "replicate"
CONDITION_KEY = "condition"
SEED_USED_KEY = "seed_used"
__all__ = ['METADATA_FILENAME', 'BASELINE_CONDITION', 'REPLICATE_KEY', 'CONDITION_KEY', 'SEED_USED_KEY']
