name: Generate and PR Docs

on:
  push:
    branches: [main]
    paths: ['crystallize/core/**'] # Only trigger if core modules change (adjust paths as needed)
  pull_request:
    branches: [main]
    paths: ['crystallize/core/**']

permissions:
  contents: write # For creating PRs
  pull-requests: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.11

      - name: Regenerate lock file
        run: pixi lock

      - name: Install dependencies
        run: pixi install -e dev

      - name: Generate docs
        run: pixi run -e dev python generate_docs.py # Adjust path if moved, e.g., scripts/generate_docs.py

      - name: Create Pull Request if changes
        uses: peter-evans/create-pull-request@v7 # Reliable action for auto-PR
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs: auto-update generated API docs'
          title: 'Auto-update generated API docs'
          body: 'This PR auto-generates and updates the API documentation Markdown files based on the latest code changes.'
          branch: auto-docs-update # Branch name for the PR
          base: main
          delete-branch: true # Clean up after merge
          labels: docs, automated
