name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.11
        with:
          pixi-version: v0.49.0
          locked: false
      - run: pixi install -e dev
      - run: pixi run -e dev test
  cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.11
        with:
          pixi-version: v0.49.0
          locked: true
      - run: pixi install -e dev
      - run: pixi run -e dev cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml # Matches --cov-report=xml output
